name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: wget https://github.com/Gamediamond3757/Overdrive/releases/download/1.0.1/Overdrive.ipa

      - name: setup siging
        run: sudo chmod +x zsign
        
      - name: sign 
        run: ./zsign -k cert.p12 -p Hydrogen -m cert.mobileprovision -o OverdriveSigned.ipa Overdrive.ipa

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: Rolling Release
          body: These are automatically updated builds of the latest commit.
          artifacts: "OverdriveSigned.ipa"
          tag: "signed"
          token: github.token
